import { User } from "../../models/User.js";
import { Student } from "../../models/Student.js";
import { TeacherActivity } from "../../models/TeacherActivity.js";
import { ApiError } from "../../utils/apiError.js";

const isAutoGeneratedTeacherEmail = (email) => String(email || "").toLowerCase().endsWith("@schoolerp.local");

const buildUniqueTeacherEmail = async (email) => {
  const normalized = String(email || "").trim().toLowerCase();
  if (!normalized || !isAutoGeneratedTeacherEmail(normalized)) return normalized;

  const [localPart] = normalized.split("@");
  const domain = "@schoolerp.local";
  let candidate = normalized;
  let suffix = 2;

  while (await User.findOne({ email: candidate, isDeleted: false }).select("_id").lean()) {
    candidate = `${localPart}.${suffix}${domain}`;
    suffix += 1;
  }

  return candidate;
};

export const registerUser = async ({
  fullName,
  email,
  password,
  role,
  actorId,
  isActive = true,
  createdAt = null,
}) => {
  const normalizedEmail = String(email || "").trim().toLowerCase();
  const uniqueEmail = await buildUniqueTeacherEmail(normalizedEmail);
  const exists = await User.findOne({ email: uniqueEmail, isDeleted: false });
  if (exists) {
    throw new ApiError(409, "Email is already in use");
  }

  const user = await User.create({
    fullName,
    email: uniqueEmail,
    password,
    role,
    isActive,
    createdBy: actorId || null,
    updatedBy: actorId || null,
  });

  const parsedCreatedAt = createdAt ? new Date(createdAt) : null;
  if (parsedCreatedAt && !Number.isNaN(parsedCreatedAt.getTime())) {
    await User.collection.updateOne(
      { _id: user._id },
      { $set: { createdAt: parsedCreatedAt, updatedAt: parsedCreatedAt } }
    );
  }

  return {
    id: user._id,
    fullName: user.fullName,
    email: user.email,
    role: user.role,
    createdAt: parsedCreatedAt && !Number.isNaN(parsedCreatedAt.getTime()) ? parsedCreatedAt : user.createdAt,
  };
};

const buildStudentAuthUser = (student) => ({
  id: student._id,
  _id: student._id,
  firstName: student.firstName || "",
  lastName: student.lastName || "",
  fullName: `${student.firstName || ""} ${student.lastName || ""}`.trim() || student.admissionNo || "Student",
  email: student.loginId || student.admissionNo || "",
  role: "STUDENT",
  admissionNo: student.admissionNo,
  rollNumber: student.rollNumber || "",
  fatherName: student.fatherName || "",
  guardianName: student.guardianName || "",
  studentPhotoUrl: student.studentPhotoUrl || null,
  className: student.className,
  section: student.section || "A",
});

const generateStudentLoginId = (student) => {
  const fullName = `${String(student.firstName || "")}${String(student.lastName || "")}`
    .replace(/[^a-z]/gi, "")
    .toLowerCase();
  if (!fullName) {
    const admission = String(student.admissionNo || "")
      .replace(/[^a-z0-9]/gi, "")
      .toLowerCase();
    return admission ? `${admission}@school.local` : `student${Date.now()}@school.local`;
  }
  return `${fullName}@gmail.com`;
};

const generateStudentLoginPassword = (student) => {
  const lettersPool =
    `${String(student.firstName || "")}${String(student.lastName || "")}`.replace(/[^a-z]/gi, "").toUpperCase() ||
    "STUDENT";
  const dobValue = student.dateOfBirth ? new Date(student.dateOfBirth) : null;
  const dobDigits =
    dobValue && !Number.isNaN(dobValue.getTime())
      ? `${dobValue.getFullYear()}${String(dobValue.getMonth() + 1).padStart(2, "0")}${String(dobValue.getDate()).padStart(2, "0")}`
      : "";
  const digitsPool =
    `${String(student.admissionNo || "")}${String(student.rollNumber || "")}${String(student.cnicBForm || "")}${dobDigits}`
      .replace(/\D/g, "") || `${Date.now()}`;
  const byPool = "BY";
  const glPool = "GL";
  const seed = `${lettersPool}|${digitsPool}|${String(student.admissionNo || "")}|BY|GL`;

  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) {
    hash = (hash * 33 + seed.charCodeAt(i)) >>> 0;
  }

  const pick = (pool, offset = 0) => pool[(hash + offset) % pool.length];
  return [
    pick(lettersPool, 0),
    pick(lettersPool, 3),
    pick(digitsPool, 1),
    pick(digitsPool, 5),
    pick(lettersPool, 7),
    pick(lettersPool, 11),
    pick(digitsPool, 13),
    pick(digitsPool, 17),
    pick(byPool, hash % byPool.length),
    pick(glPool, (hash + 1) % glPool.length),
  ]
    .join("")
    .slice(0, 10);
};

export const loginUser = async ({ email, password, role }) => {
  const requestedRole = String(role || "ACCOUNTANT").trim().toUpperCase();
  const normalizedLogin = String(email || "").trim().toLowerCase();

  if (requestedRole === "STUDENT") {
    const students = await Student.find({
      isDeleted: false,
      status: "ACTIVE",
      portalAccessEnabled: true,
    })
      .select("_id firstName lastName fatherName guardianName admissionNo className section loginId loginPassword rollNumber cnicBForm dateOfBirth status studentPhotoUrl")
      .lean();

    const student = students.find((row) => {
      const storedLoginId = String(row.loginId || "").trim().toLowerCase();
      const generatedLoginId = generateStudentLoginId(row);
      const admissionNo = String(row.admissionNo || "").trim().toLowerCase();
      const rollNumber = String(row.rollNumber || "").trim().toLowerCase();
      return (
        normalizedLogin === storedLoginId ||
        normalizedLogin === generatedLoginId ||
        normalizedLogin === admissionNo ||
        normalizedLogin === rollNumber
      );
    });

    if (!student) {
      throw new ApiError(401, "Invalid credentials");
    }

    const expectedPassword = String(student.loginPassword || "").trim() || generateStudentLoginPassword(student);
    if (expectedPassword !== String(password || "")) {
      throw new ApiError(401, "Invalid credentials");
    }

    return {
      user: buildStudentAuthUser(student),
    };
  }

  const user = await User.findOne({ email: normalizedLogin, isDeleted: false }).select("+password");

  if (!user || !user.isActive) {
    throw new ApiError(401, "Invalid credentials");
  }

  if (requestedRole !== user.role) {
    throw new ApiError(403, "Invalid portal for this account");
  }

  const passwordOk = await user.comparePassword(password);
  if (!passwordOk) {
    throw new ApiError(401, "Invalid credentials");
  }

  if (user.role === "TEACHER") {
    TeacherActivity.create({
      teacherId: user._id,
      action: "LOGIN",
      module: "AUTH",
      details: "Teacher logged in",
      status: "SUCCESS",
      createdBy: user._id.toString(),
      updatedBy: user._id.toString(),
    }).catch(() => {});
  }

  return {
    user: {
      id: user._id,
      fullName: user.fullName,
      email: user.email,
      role: user.role,
    },
  };
};

export const logoutUser = async (session) =>
  new Promise((resolve, reject) => {
    if (!session) {
      resolve();
      return;
    }
    session.destroy((err) => {
      if (err) reject(err);
      else resolve();
    });
  });

export const getMySignature = async (userId) => {
  const user = await User.findOne({ _id: userId, isDeleted: false }).select("signatureDataUrl").lean();
  if (!user) throw new ApiError(404, "User not found");
  return { signatureDataUrl: user.signatureDataUrl || "" };
};

export const saveMySignature = async (userId, signatureDataUrl = "") => {
  const value = String(signatureDataUrl || "").trim();
  if (value && !value.startsWith("data:image/")) {
    throw new ApiError(400, "Invalid signature image");
  }

  const user = await User.findOneAndUpdate(
    { _id: userId, isDeleted: false },
    { $set: { signatureDataUrl: value, updatedBy: userId.toString() } },
    { new: true }
  )
    .select("signatureDataUrl")
    .lean();

  if (!user) throw new ApiError(404, "User not found");
  return { signatureDataUrl: user.signatureDataUrl || "" };
};
