export const ASSET_CATEGORIES = [
  "DESKS",
  "TABLES",
  "CHAIRS",
  "BENCHES",
  "BENCHES_CHAIRS",
  "TEACHER_TABLES",
  "TEACHER_CHAIRS",
  "WHITE_BOARDS",
  "BLACK_BOARDS",
  "FANS",
  "BULBS",
  "TUBE_LIGHTS",
  "AIR_CONDITIONERS",
  "PROJECTORS",
  "COMPUTERS",
  "PRINTERS",
  "WATER_COOLERS",
  "CCTV_CAMERAS",
  "UPS",
  "GENERATORS",
  "LAB_EQUIPMENT",
  "LIBRARY_FURNITURE",
  "OFFICE_FURNITURE",
  "OTHER",
];

export const FURNITURE_CATEGORIES = [
  "DESKS",
  "TABLES",
  "CHAIRS",
  "BENCHES",
  "BENCHES_CHAIRS",
  "TEACHER_TABLES",
  "TEACHER_CHAIRS",
  "WHITE_BOARDS",
  "BLACK_BOARDS",
  "LIBRARY_FURNITURE",
  "OFFICE_FURNITURE",
];

export const ASSET_CATEGORY_LABELS = {
  DESKS: "Desks",
  TABLES: "Tables",
  CHAIRS: "Chairs",
  BENCHES: "Benches",
  BENCHES_CHAIRS: "Benches & Chairs",
  TEACHER_TABLES: "Teacher Tables",
  TEACHER_CHAIRS: "Teacher Chairs",
  WHITE_BOARDS: "White Boards",
  BLACK_BOARDS: "Black Boards",
  FANS: "Fans",
  BULBS: "Bulbs",
  TUBE_LIGHTS: "Tube Lights",
  AIR_CONDITIONERS: "Air Conditioners",
  PROJECTORS: "Projectors",
  COMPUTERS: "Computers",
  PRINTERS: "Printers",
  WATER_COOLERS: "Water Coolers",
  CCTV_CAMERAS: "CCTV Cameras",
  UPS: "UPS",
  GENERATORS: "Generators",
  LAB_EQUIPMENT: "Laboratory Equipment",
  LIBRARY_FURNITURE: "Library Furniture",
  OFFICE_FURNITURE: "Office Furniture",
  OTHER: "Other",
};

export const ASSET_STATUSES = ["WORKING", "BROKEN", "UNDER_MAINTENANCE", "MISSING", "REPLACED"];

export const getAssetCategoryLabel = (value) => ASSET_CATEGORY_LABELS[value] || value;
